# Generated by Django 5.2.4 on 2025-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("base_lot_size", models.FloatField()),
                ("target_win_rate", models.FloatField()),
                ("target_rr", models.FloatField()),
                ("reference_volatility", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("symbol", models.CharField(max_length=20)),
                ("volume", models.FloatField()),
                ("entry_price", models.FloatField()),
                ("exit_price", models.FloatField()),
                ("profit", models.FloatField()),
                (
                    "account_type",
                    models.CharField(
                        choices=[("Funded", "Funded"), ("Personal", "Personal")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
