# Generated by Django 5.2.4 on 2025-07-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskwise", "0002_alter_trade_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="screenshots/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
