# Generated by Django 5.2.4 on 2025-07-07 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskwise", "0003_screenshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="riskwise.strategy",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="strategy",
            name="reference_volatility",
            field=models.FloatField(help_text="Reference volatility measure"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="target_rr",
            field=models.FloatField(help_text="Target Risk/Reward Ratio"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="target_win_rate",
            field=models.FloatField(help_text="Expected win rate (%)"),
        ),
        migrations.CreateModel(
            name="DailyTradeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("trade_name", models.CharField(max_length=200)),
                ("risk_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("profit_loss", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("Funded", "Funded"), ("Personal", "Personal")],
                        max_length=10,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "risk_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Default % risk per trade",
                        max_digits=5,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
