# Generated by Django 5.2.4 on 2025-07-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskwise", "0005_simulationhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationhistory",
            name="chart",
        ),
        migrations.AddField(
            model_name="simulationhistory",
            name="chart_base64",
            field=models.TextField(default=("",)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simulationhistory",
            name="label",
            field=models.CharField(max_length=100),
        ),
    ]
