# Generated by Django 5.2.4 on 2025-07-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskwise", "0006_remove_simulationhistory_chart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationhistory",
            name="tags",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
